transfer

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,29 @@
 #!/usr/bin/env bash
-# transfers a file from a client to a server with scp
+# checking for command line arguments
 
-if [ "$#" -lt 3 ]; then
+
+if [ "$#" -lt 3 ];
+then
 	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ]; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+	exit 1
+fi
+
+# assigning parametals to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_shh_key=$4
+
+# disabbling strict host key checking
+
+scp -0 "StrictHostKeyChecking=no" -i "path_to_shh_key" "$path_to_file" "$username@$ip:~/"
+
+
+# checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "FILE WAS TRANSFERED SUCCESSFULLY"
 else
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+	echo "FILE TRANSFER FAILED"
 fi
